#!/bin/bash -e
# Update package sources

echo "deb http://deb.openswitch.net/$DIST $OPX_RELEASE main opx opx-non-free" \
  >> /etc/apt/sources.list.d/opx.list

if [[ "$DIST" == "jessie" ]]; then
  echo "deb http://deb.openswitch.net/contrib stable contrib" \
    >> /etc/apt/sources.list.d/opx.list
fi

if [[ "$OPX_RELEASE" =~ ^(unstable|testing|stable)$ ]]; then
  echo "deb-src http://deb.openswitch.net/$DIST $OPX_RELEASE opx" \
    >>/etc/apt/sources.list.d/opx.list
fi

apt-get -qq update
