#!/bin/bash

# Create the APT Packages (index) file for all local packages

DIST="unstable"
COMP="main"
ARCH="amd64"

[[ $# -gt 0 ]] && {
  DIST="$1"
}

LOC="dists/$DIST/$COMP/binary-$ARCH"

rm -fr dists
mkdir -p "$LOC/"
dpkg-scanpackages -m . >"$LOC/Packages"
