#!/bin/bash
#
# Copyright (c) 2015 Dell Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# THIS CODE IS PROVIDED ON AN #AS IS* BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
#  LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS
# FOR A PARTICULAR PURPOSE, MERCHANTABLITY OR NON-INFRINGEMENT.
#
# See the Apache Version 2.0 License for specific language governing
# permissions and limitations under the License.
#

which docker 2>/dev/null >&2

if [ ! $? = 0 ] ; then
  echo "You will need to install dockers for this to work."
  exit 1
fi

ID=$(docker ps -f ancestor=docker-opx --format "{{.ID}}")

if [ "${ID}b" = b ] ; then
  docker build -t docker-opx -f opx_build_Dockerfile .
fi

echo "OPX Docker Image"
docker ps -f ancestor=docker-opx 

export PATH=$(dirname $1):$PATH

