#!/bin/bash

# default package distribution
export OPX_RELEASE=${OPX_RELEASE-unstable}
# currently tracked release
export DEBIAN_DIST=${DEBIAN_DIST-jessie}
# docker image tag
VERSION="${VERSION-latest}"
# docker image name
IMAGE="opxhub/build"

# Available Options
OPX_GIT_TAG=${OPX_GIT_TAG-no}
OPX_POOL_PACKAGES=${OPX_POOL_PACKAGES-no}

interactive="-i"
if [ -t 1 ]; then
    # STDOUT is attached to TTY
    interactive="-it"
fi

read -d '' opx_docker_command <<- EOF
docker run
    --rm
    --name ${USER}_$(basename $PWD)_$$
    --privileged
    -e LOCAL_UID=$(id -u ${USER})
    -e LOCAL_GID=$(id -g ${USER})
    -v ${PWD}:/mnt
    -v $HOME/.gitconfig:/home/opx/.gitconfig
    -v /etc/localtime:/etc/localtime:ro
    -e DEBIAN_DIST
    -e OPX_RELEASE
    -e OPX_GIT_TAG
    -e OPX_POOL_PACKAGES
    ${interactive}
    ${IMAGE}:${VERSION}
EOF

if [[ $# -gt 0 ]]; then
    # run command directly
    $opx_docker_command sh -c "$*"
else
    # launch interactive shell
    $opx_docker_command
fi
