#!/bin/bash -e
# Pull packages from Bintray if not available locally

DEBIAN_FRONTEND=noninteractive apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y curl
curl -fsSL https://bintray.com/user/downloadSubjectPublicKey?username=dell-networking | apt-key add -
curl -fsSL https://bintray.com/user/downloadSubjectPublicKey?username=open-switch | apt-key add -
echo "deb http://dell-networking.bintray.com/opx-apt unstable main" | tee -a /etc/apt/sources.list
echo "deb http://dl.bintray.com/open-switch/opx-apt unstable main" | tee -a /etc/apt/sources.list
apt-get update
